version: "3.8"

services:
  puter:
    image: ghcr.io/heyputer/puter:latest
    restart: unless-stopped
    ports:
      - '10000:4100'
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4100/test || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
