services:
  - type: web
    name: puter
    env: docker
    dockerComposePath: ./docker-compose.yml
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
