version: "1"

services:
  - type: web
    name: puter
    runtime: image
    image:
      url: ghcr.io/heyputer/puter:latest
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: "10000"
    region: oregon
